### ISSUE TITLE
Directory is created using windows path format on macosx

### ISSUE THREAD

**Issue by NocturnScholar** [KiritchoukC/vscode-ext_flutter-clean-architecture#1]
Hello,
I'm using this VSCode extension on Macosx. 

When creating new feature, it creates new directory using Windows path format. 
So, instead of creating "login" directory inside "features", it creates new "lib\features" directory ("\\" character is part of the directory name) as parent directory and proceeds to creating "login" directory inside it.

here's how the directory tree structure looked like after adding "login" feature:

![Screen Shot 2019-11-26 at 9 58 49 AM](https://user-images.githubusercontent.com/46780363/69595895-64476b00-1033-11ea-9d4d-76e980b1bcd0.png)

**Comment by KiritchoukC** [comment]
Hello @NocturnScholar,

Indeed, I am using Windows and did not test it on MacOs.

I'll fix it asap, thanks for letting me know.

**Comment by KiritchoukC** [comment]
The extension has been updated.

Tell me if this fixed it for you and I'll close the issue

**Comment by NocturnScholar** [comment]
Using the updated version fixed this issue. 
Tested it using context menu and command palette, all feature related directories are created in the selected parent directory. 

Thank you.

**Comment by KiritchoukC** [comment]
Awesome!

Thanks for testing
