### ISSUE TITLE
[BUG] Unsupported version of equatable

### ISSUE THREAD

**Issue by TheFabbiusCorp** [KiritchoukC/vscode-ext_flutter-clean-architecture#15]
I'm getting the following error every time I run VSCode on a project where this shouldn't happen:

![image](https://user-images.githubusercontent.com/8267992/115118939-22132680-9fa6-11eb-9bc9-0f45b053bfdf.png)

## Expected Behavior
Do not get notified.

## Current Behavior
Unwanted notification.

## Possible Solution
Update version checker(?).

## Steps to Reproduce
Using the latest version on VSCode, every time VSCode is run on a Flutter project.

## Context (Environment)
Generic startup.

## Possible Implementation
Fix version check.

Thank you! 😊

**Comment by KiritchoukC** [comment]
Hi @TheFabbiusCorp ,

Thanks for raising this issue.
I'll fix it this week.
