### ISSUE TITLE
[BUG] Unsupported flutter_bloc and hydrated_bloc version

### ISSUE THREAD

**Issue by TheFabbiusCorp** [KiritchoukC/vscode-ext_flutter-clean-architecture#17]
Hi again, I think the plugin needs to be updated since I'm running version 7.0.0 of the aforementioned packages but the plugin wants me to "update" to 6.0.0.

## Expected Behavior
No notification.

## Current Behavior
False notification of update needed.

![image](https://user-images.githubusercontent.com/8267992/125804590-dd5cb145-61eb-4f8a-9079-812047b44efe.png)

## Possible Solution
Update plugin.

## Steps to Reproduce
Plugin active + version 7.0.0 of flutter_bloc and hydrated_bloc packages in yaml file.

**Comment by TheFabbiusCorp** [comment]
Hi @KiritchoukC , do you think you'll have time to take a look into it? 🙏🏼

**Comment by KiritchoukC** [comment]
Hi @TheFabbiusCorp,
It will be done by the end of the week.

**Comment by KiritchoukC** [comment]
fixed by commits:
8e8c2cfb11a94967c972d76c087147686891e8d0
0424436649fd13725a969e94bcc6d73824a92a99

Any feedback is appreciated 🙂
