### ISSUE TITLE
[BUG] Incompatible version error prompt

### ISSUE THREAD

**Issue by KiritchoukC** [KiritchoukC/vscode-ext_flutter-clean-architecture#2]
2 notifications prompts when enabling the extension

## Expected Behavior
Everything should be fine if package meets the requirements

## Current Behavior
Even with minimal version of needed package, there's an error when activating the extension

## Steps to Reproduce
_Provide a link to a live example, or an unambiguous set of steps to_
_reproduce this bug. Include code to reproduce, if relevant_
1. Create new Flutter project
2. Add these dependencies to **pubspec.yaml** file
  - flutter_bloc: ^3.2.0
  - equatable: ^1.1.0
3. Activate the extension or Deactivate/Activate
4. 2 notifications prompts

## Context (Environment)
This error should not prevent the user from using the extension

**Comment by winsuseno** [comment]
I'm grateful for your having developed this Flutter Feature Scaffolding VS Code extension. It's helped save a lot of time starting Flutter projects using the Clean Architecture.

I look forward to having this issue resolved.

**Comment by excogitatr** [comment]
Fixed in #3
