### ISSUE TITLE
[BUG] Create .gitkeep files in all empty folders

### ISSUE THREAD

**Issue by Mithrandir2k18** [KiritchoukC/vscode-ext_flutter-clean-architecture#6]
When creating a feature all the empty folders cannot be commited to a git repository, because git only recognizes folders by pathnames of existing files. So each leaf folder of the feature folder tree structure should contain an empty file called `.gitkeep` as shown in resocoders newer DDD course.

## Possible Implementation
Generate empty `.gitkeep` files in all leaf folders of the tree structure.

**Comment by KiritchoukC** [comment]
Hi @Mithrandir2k18 

This extension is not meant to be used with git only.
I know git is the most used VCS but I don't think it's a good idea to force users of the extension to use Git.

Let me know what your think about that

**Comment by Mithrandir2k18** [comment]
@KiritchoukC 

Well, the BLoC extension for example asks you if you want to use Equatable or not with a 2nd prompt. Why not do the same, a prompt that asks if we want to create GitKeep Files as well?

**Comment by KiritchoukC** [comment]
#7 Open for anyone that wants this feature implemented 😃
