### ISSUE TITLE
[BUG] extension recommends updating when packages are newer

### ISSUE THREAD

**Issue by gcamp806** [KiritchoukC/vscode-ext_flutter-clean-architecture#9]
If the packages in pubspec.yaml are more recent than what this plugin knows about, the plugin suggests the packages should be upgraded (which would actually be a downgrade).

## Expected Behavior
If the packages in pubspec.yaml are newer, then the plugin should not display a warning

## Current Behavior
bloc_test - please update to ^6.0.0
(however, the current version is ^7.0.6)
If the user clicks the "Update" button, then pubspec.yaml is downgrading the version and breaking other package dependencies.

## Possible Solution
Ignore newer versions of the plugins

## Steps to Reproduce
Open a project that uses newer versions of bloc, bloc_test, flutter_bloc

**Comment by KiritchoukC** [comment]
Hi @gcamp806,

I will look at this tomorrow and release a new version asap. 

Thanks for raising this issue.
